start_time: 2020-01-01
end_time: 2025-5-31
min_price: 7
max_price: 28
min_market_cap: 30
max_market_cap: 300
initial_capital: 100000
zy_rate: 1.3
zs_rate: 0.6
log_file: backtest_log.txt
ma_line: ma10
zy_ma_line: ma20
region: ['浙江板块']
not_market_type: ['创业板', '科创板']
max_stock_num: 100
index_code: 000001.SH
random_seed: 666

# sql
sql:
  host: localhost
  port: 3306
  user: afei
  password: sf123456
  database: stock

show_progress: True
